"""README quality / completeness heuristics."""

from __future__ import annotations

from friday.readme import readme_completeness, readme_quality


def test_none():
    assert readme_quality(None) == "none"
    assert readme_completeness(None) == "none"


def test_boilerplate_short():
    assert readme_quality("# My Project\n\nTODO") == "boilerplate"


def test_boilerplate_template_phrase():
    text = "# Starter\n\nThis is a template generated by create-app. Welcome to your new project!"
    assert readme_quality(text) == "boilerplate"


def test_good():
    text = (
        "# Aether\n\nAether is an AI-native operating system built in Rust.\n\n"
        "## Features\n- Scheduler\n- Memory manager\n\n## Roadmap\n- Networking\n"
    )
    assert readme_quality(text) == "good"
    assert readme_completeness(text) == "complete"


def test_poor_thin():
    # Present and reasonably long, but no features/roadmap and only a thin purpose.
    text = (
        "# X\n\nX is a project that does a few things for the user. "
        "It was started recently and is still being shaped. "
        "More documentation will be written as it matures."
    )
    assert readme_quality(text) == "poor"


def test_partial():
    text = "# X\n\nX is a tool for managing deployments."
    assert readme_completeness(text) == "partial"
